wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: LSTM
train_set:
  desc: null
  value: <custom_example.AlternatingSignalDataset object at 0x7f04f1587f50>
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717965153.330897
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 5
      13: linux-x86_64
