wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: LSTM
train_set:
  desc: null
  value: <__main__.AlternatingSignalDataset object at 0x7fb48ed0b290>
epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718057842.470002
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 5
      13: linux-x86_64
