wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: S4D
train_set:
  desc: null
  value: <__main__.AlternatingSignalDataset object at 0x7f09f8c78210>
epochs:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717620447.540232
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
